version: "3.8"

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
      - /app/venv
    environment:
      - PYTHONPATH=/app/src
      - DATABASE_URL=${DATABASE_URL:-postgresql://crispr:password@db:5432/crispr_toolkit}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - CRISPR_ENV=${CRISPR_ENV:-development}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      - db
      - redis
    command: uvicorn crispr_toolkit.api.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-crispr_toolkit}
      - POSTGRES_USER=${POSTGRES_USER:-crispr}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  jupyter:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ..:/app
      - /app/venv
    environment:
      - PYTHONPATH=/app/src
      - CRISPR_ENV=${CRISPR_ENV:-development}
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --notebook-dir=/app

volumes:
  postgres_data:
  redis_data:
  redis_data:
